- id: '1641148775267'
  alias: Doorbell ring cast
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 44174a413f54a08635deec721297261d
    entity_id: binary_sensor.nuki_main_door_ring_action
    domain: binary_sensor
  condition: []
  action:
  - service: cast.show_lovelace_view
    data:
      entity_id: media_player.living_room_display
      dashboard_path: ipad-dashboard
  mode: single
- id: '1683998026475'
  alias: Entrance Motion Lights
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.entrance_motion
      light_target:
        area_id: a10e00371bf64611a80b9bf5e73a0b38
