version: '3'
services:
    homeassistant:
        container_name: home-assistant
        environment:
            - TZ=Europe/Madrid
        volumes:
            - '/home/homeassistant/.homeassistant:/config'
            - '/home/homeassistant/dehydrated:/srv/dehydrated'
        image: 'homeassistant/raspberrypi3-homeassistant:stable'
        network_mode: host
        restart: always