version: '3'
services:
    homeassistant:
        container_name: home-assistant
        environment:
            - TZ=Europe/Madrid
        volumes:
            - '/home/homeassistant/.homeassistant:/config'
            - '/home/homeassistant/dehydrated:/srv/dehydrated'
        build:
            dockerfile: ./Dockerfile
            context: patch_homeassistant/
        network_mode: host
        restart: always