version: '3'
services:
    homeassistant:
        container_name: home-assistant
        environment:
            - TZ=Europe/Madrid
        volumes:
            - '/home/homeassistant/.homeassistant:/config'
            - '/home/homeassistant/dehydrated:/srv/dehydrated'
        build:
            dockerfile: ./Dockerfile
            context: patch_homeassistant/
        network_mode: host
        restart: always
    google-assistant-relay:
        container_name: assistant_relay
        image: 'tijunoi/rpi-assistant-relay'
        command: npm run start
        volumes:
            - '/home/homeassistant/.homeassistant/assistant_relay/config.json:/assistant_relay/bin/config.json:rw'
            - '/home/homeassistant/.homeassistant/assistant_relay/audio-responses:/assistant_relay/bin/audio-responses:rw'
        ports:
            - '3000:3000'
        restart: always
    deconz:
        container_name: deconz
        image: marthoc/deconz
        network_mode: host
        restart: always
        volumes:
            - '/home/homeassistant/deconz:/root/.local/share/dresden-elektronik/deCONZ'
            - '/etc/localtime:/etc/localtime:ro'
        devices:
            - /dev/ttyACM0
        environment:
            - DECONZ_DEVICE=/dev/ttyACM0
            - DECONZ_WEB_PORT=8080
            - DECONZ_WS_PORT=8443
            - DEBUG_INFO=1
            - TZ=Europe/Madrid
            - DECONZ_VNC_MODE=1
    webserver:
        container_name: webserver
        image: 'httpd:2.4'
        volumes: 
            - '/home/homeassistant/.homeassistant/www/:/usr/local/apache2/htdocs'
        ports:
            - 8084:80
        restart: always
    homebridge:
        container_name: homebridge
        image: oznu/homebridge:no-avahi
        restart: always
        network_mode: host
        environment:
            - TZ=Europe/Madrid
            - PGID=1001
            - PUID=1001
            - HOMEBRIDGE_CONFIG_UI=1
            - HOMEBRIDGE_CONFIG_UI_PORT=8085
        volumes:
            - '/home/homeassistant/.homeassistant/homebridge:/homebridge'
    portainer:
        image: portainer/portainer:arm
        restart: always
        volumes: 
            - '/var/run/docker.sock:/var/run/docker.sock'
        expose:
            - 9000
        ports:
            - 8083:9000
    mqtt:
        container_name: mqtt
        image: eclipse-mosquitto
        restart: unless-stopped
        user: '1001'
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - './mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf'
            - '/home/homeassistant/mosquitto/data:/mosquitto/data'
    valetudo-mapper:
        container_name: valetudo-mapper
        image: rand256/valetudo-mapper
        restart: always
        volumes:
            - './valetudo-mapper/config.json:/app/config.json'
    backup:
        container_name: backup
        image: linuxserver/duplicati
        restart: always
        environment:
         - PUID=1001
         - PGID=1001
         - TZ=Europe/Madrid
        volumes:
         - '/home/homeassistant/.homeassistant/duplicati:/config'
         - '/home/homeassistant:/source'
        ports:
         - 8200:8200
