version: '3'
services:
    homeassistant:
        container_name: home-assistant
        environment:
            - TZ=Europe/Madrid
        volumes:
            - './:/config'
        build:
            dockerfile: ./Dockerfile
            context: patch_homeassistant/
            args:
              IMAGE: homeassistant/home-assistant:0.114.4
        command: python -m homeassistant --script check_config --config /config --info all
