version: '3'
services:
    homeassistant:
        container_name: home-assistant
        environment:
            - TZ=Europe/Madrid
        volumes:
            - '/home/homeassistant/.homeassistant:/config'
            - '/home/homeassistant/dehydrated:/srv/dehydrated'
        build:
            dockerfile: ./Dockerfile
            context: patch_homeassistant/
        network_mode: host
        restart: always
    google-assistant-relay:
        container_name: assistant_relay
        build:
            dockerfile: ./Dockerfile
            context: assistant_relay
        volumes:
            - '/home/homeassistant/.homeassistant/assistant_relay/config.json:/assistant_relay/bin/config.json:rw'
            - '/home/homeassistant/.homeassistant/assistant_relay/audio-responses:/assistant_relay/bin/audio-responses:rw'
        ports:
            - '3000:3000'
        restart: always