version: 2
jobs:
  check-config:
    machine: true
#    docker:
#      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check config
          command: |
            touch fake.pem
            mv circleci_secrets.yaml secrets.yaml
            mkdir google-assistant
            touch google-assistant/service_account.json
            docker-compose -f docker-compose.check.yaml up --build --force-recreate --exit-code-from homeassistant
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:b7:45:ee:8e:25:53:24:b5:f2:0d:3e:f2:37:7d:d0"
      - run:
          name: Deploy Over SSH
          command: |
            ssh ${SSH_USER}@${SSH_HOST} "cd /home/homeassistant/.homeassistant && sudo -u homeassistant git pull && sudo -u homeassistant docker-compose up -d --build homeassistant"

workflows:
  version: 2
  check-config-and-deploy:
    jobs:
      - check-config
      - deploy:
          requires:
            - check-config
          filters:
            branches:
              only: master
