version: 2
jobs:
  build:
    docker:
      - image: homeassistant/home-assistant:0.97.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check config
          command: |
            touch fake.pem
            mv circleci_secrets.yaml secrets.yaml
            hass -c . --script check_config --info all
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:b7:45:ee:8e:25:53:24:b5:f2:0d:3e:f2:37:7d:d0"
      - run:
          name: Deploy Over SSH
          command: |
            ssh ${SSH_USER}@${SSH_HOST} "cd /home/homeassistant/.homeassistant && sudo -u homeassistant git pull && sudo systemctl restart home-assistant@homeassistant.service"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master