- alias: 'Try reconnect to Dyson fan if unavailable for 3 hours'
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('climate.bedroom', 'available', false) }}"
      for: "03:00:00"
  action:
    service: dyson.reconnect
    entity_id: climate.bedroom

- alias: 'Notify Nil when Home Assistant is started (usually from a deploy restart)'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.mobile_app_nils_iphone_xs
    data:
      message: "Home Assistant has been started"
      title: "Home Assistant started"
      data:
        push:
          thread-id: "homeassistant-server-status"

- alias: "Notify phones when iPad battery is running low"
  trigger:
    platform: numeric_state
    entity_id: sensor.ipad_battery_level
    below: 10
  action:
    - service: notify.iphones
      data:
        message: "Charge iPad soon to keep Homekit hub running"
        title: "iPad battery low ({{ states('sensor.ipad_battery_level') }}%)"
        data:
          push:
            thread-id: "ipad-battery-status"
    - condition: state
      entity_id: binary_sensor.someone_home
      state: 'on'
    - service: rest_command.assistant_broadcast
      data:
        command: "iPad battery low. Charge iPad soon to keep Homekit hub running"

# Christmas lights automations
- alias: 'Switch on the balcony christmas lights at night'
  trigger:
    platform: time_pattern
    seconds: "/30"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '17:30:00'
        before: '07:30:00'
      - condition: state
        entity_id: light.christmas_balcony
        state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.christmas_balcony

- alias: 'Switch off the balcony christmas lights by day'
  trigger:
    platform: time_pattern
    seconds: "/30"
  condition:
    condition: and
    conditions:
      - condition: time
        before: '17:30:00'
        after: '07:30:00'
      - condition: state
        entity_id: light.christmas_balcony
        state: 'on'
  action:
    service: light.turn_off
    data:
      entity_id: light.christmas_balcony

- id: "dishwasher_notify_finished"
  alias: Notify when dishwasher timer has finished.
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.dishwasher
  action:
      - service: rest_command.assistant_broadcast
        data:
          command: "Dishwasher has finished."
 
- id: '1607677760156'
  alias: 'Office light remote: Toggle light'
  description: ''
  trigger:
  - device_id: e12b733b0f9f47bfb6147d27781abc28
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: 9e46d317a9c7e084ee9c88e847ad7c6f
    entity_id: light.office
    domain: light
  mode: single
